"""Generate data_loader/cpp/pawn_vocab.h from the frequency-sorted vocab files.

Reads out_attr/pawn_structures_{left,right}_vocab.txt (lines: count<tab>pct<tab>fen
where fen is rank8..rank1, '/'-separated, P=one side p=mirror), reconstructs each
structure's (a,b) bitboards exactly as pawn_structs_mt.cpp canonicalized them, and
writes a header with frequency-ordered {a,b} arrays. The array index IS the feature
index used by both the data loader and the model.

Usage: python gen_pawn_vocab.py [--max N] [--out path]
"""
import argparse

LEFT_FILES = (0, 3)
RIGHT_FILES = (4, 7)


def fen_to_bitboards(fen: str, f0: int, f1: int) -> tuple[int, int]:
    """Inverse of fen_pawns(): ranks listed 8->1, files f0..f1 per rank."""
    a = b = 0
    ranks = fen.split("/")
    assert len(ranks) == 8, fen
    for ri, row in enumerate(ranks):
        r = 7 - ri  # first token is rank 8 (index 7)
        assert len(row) == (f1 - f0 + 1), (fen, row)
        for fi, ch in enumerate(row):
            f = f0 + fi
            bit = r * 8 + f
            if ch == "P":
                a |= 1 << bit
            elif ch == "p":
                b |= 1 << bit
            else:
                assert ch == ".", ch
    return a, b


def read_vocab(path: str, files: tuple[int, int], maxn: int) -> list[tuple[int, int]]:
    out = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("#") or not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            fen = parts[2]
            out.append(fen_to_bitboards(fen, *files))
            if len(out) >= maxn:
                break
    return out


def emit_array(name: str, entries: list[tuple[int, int]]) -> str:
    lines = [f"inline constexpr std::uint64_t {name}[][2] = {{"]
    for a, b in entries:
        lines.append(f"    {{0x{a:016x}ULL, 0x{b:016x}ULL}},")
    lines.append("};")
    lines.append(f"inline constexpr std::size_t {name}_SIZE = {len(entries)};")
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--max", type=int, default=20000, help="max structures embedded per side")
    p.add_argument("--left", default="out_attr/pawn_structures_left_vocab.txt")
    p.add_argument("--right", default="out_attr/pawn_structures_right_vocab.txt")
    p.add_argument("--out", default="data_loader/cpp/pawn_vocab.h")
    args = p.parse_args()

    left = read_vocab(args.left, LEFT_FILES, args.max)
    right = read_vocab(args.right, RIGHT_FILES, args.max)

    header = f"""// Auto-generated by gen_pawn_vocab.py -- DO NOT EDIT.
// Frequency-ordered pawn-structure vocabulary. Index = feature index.
// Each entry is {{own_or_P_bitboard, enemy_or_p_bitboard}} in canonical (flip-side)
// form, restricted to one half-board (left=files a-d, right=files e-h).
#ifndef PAWN_VOCAB_H_INCLUDED
#define PAWN_VOCAB_H_INCLUDED

#include <cstdint>
#include <cstddef>

{emit_array("PAWN_VOCAB_LEFT", left)}

{emit_array("PAWN_VOCAB_RIGHT", right)}

#endif  // PAWN_VOCAB_H_INCLUDED
"""
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(header)
    print(f"wrote {args.out}: left={len(left)} right={len(right)} (max {args.max})")


if __name__ == "__main__":
    main()
